### ISSUE TITLE
Browser is reloading instead of hot reloading

### ISSUE THREAD

**Issue by ikristher** [phleobon/laravel-elixir-browserify-hmr#1]
Hello new to browserify and hot reloading, can you help me with my problem. I am using laravel-elixir for a custom project (not in Laravel). I already downloaded the dependencies, but everytime I make changes, the whole window is reloading instead of components. I am saving the outputs to /css and /js folder

here is my gulpfile, Thank you

```
var elixir = require('laravel-elixir');

require('laravel-elixir-vueify');
require('laravel-elixir-browserify-hmr');

elixir(function (mix) {
	mix.sass('app.scss', 'css/').browserify('app.js', 'js').browserSync({
		proxy: 'http://domain.dev',
		files:[
			'css/**/*',
			'js/**/*'
		]
	});
});
```

**Comment by ikristher** [comment]
I got it now, I should remove the js folder from the files option for browsersync.

**Comment by phleobon** [comment]
@ikristher Another solution would be to access directly http://domain.dev while having gulp in watch mode.
